secretGenerator:
- name: mysql-pass
  literals:
  - password=YOUR_PASSWORD
resources:
  - mysql-deployment.yaml
  - mysql-pvc.yaml
  - mysql-service.yaml
  - wp-deployment.yaml
  - wp-pvc.yaml
  - wp-service.yaml
