apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: wordpress
    tier: frontend
  